# Run with: fontforge -script scripts/build_icons_font.py icons out
# Requires FontForge with Python scripting enabled.

import fontforge
import os
import sys
import re
import argparse

PUA_START = 0xE000
FONT_NAME = "simple-ime-icons"
EM_SIZE = 1000  # font units per em
VIEWPORT = EM_SIZE  # 1000
CONTENT = EM_SIZE * 20.0 / 24.0  # ~833.33
PADDING = EM_SIZE * 2.0 / 24.0  # ~83.33

ASCENT = EM_SIZE
DESCENT = abs(EM_SIZE - ASCENT)

def to_macro_name(filename: str) -> str:
    base = os.path.splitext(os.path.basename(filename))[0]
    base = re.sub(r'[^0-9a-zA-Z]+', '_', base).strip('_').upper()
    if not base:
        base = "ICON"
    if base[0].isdigit():
        base = "_" + base
    return "ICON_" + base


def main():
    if len(sys.argv) < 7:
        print("Usage: fontforge -script build_icons_font.py --icons_dir <icons_dir> --list <icons list> --out <out_dir>")
        sys.exit(2)

    ap = argparse.ArgumentParser()
    ap.add_argument("--icons_dir", required=True, help="Path to icons directory (contains *.svg)")
    ap.add_argument("--list", required=True, help="Text file with icon names (one per line)")
    ap.add_argument("--out", required=True, help="Output directory for TTF and icons.h")
    args = ap.parse_args()

    icons_dir = os.path.abspath(args.icons_dir)
    out_dir = os.path.abspath(args.out)
    os.makedirs(out_dir, exist_ok=True)

    if not os.path.isdir(icons_dir):
        print("Lucide icons dir not found:", icons_dir, file=sys.stderr)
        return 2

    with open(args.list, "r", encoding="utf-8") as f:
        names = []
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            names.append(s)

    missing = []
    svgs = []
    for name in names:
        src = os.path.join(icons_dir, f"{name}.svg")
        if not os.path.isfile(src):
            missing.append(name)
            continue
        svgs.append(src)

    if missing:
        print("Missing icons in lucide dir:", ", ".join(missing), file=sys.stderr)
        return 1

    if not svgs:
        print("No any expected SVG files found in", icons_dir)
        return 1

    svgs.sort()

    font = fontforge.font()
    font.encoding = "UnicodeFull"
    font.em = EM_SIZE
    font.ascent = ASCENT
    font.descent = DESCENT

    font.fontname = FONT_NAME
    font.fullname = FONT_NAME
    font.familyname = FONT_NAME

    mappings = []  # (macro, codepoint, filename)

    for i, svg_path in enumerate(svgs):
        codepoint = PUA_START + i
        g = font.createChar(codepoint)
        g.glyphname = to_macro_name(svg_path).lower()

        g.importOutlines(svg_path)

        # Basic cleanup
        g.removeOverlap()
        g.correctDirection()

        # Scale glyph to target height
        xmin, ymin, xmax, ymax = g.boundingBox()
        h = (ymax - ymin) if (ymax - ymin) != 0 else 1
        w = (xmax - xmin) if (xmax - xmin) != 0 else 1
        scale = min(CONTENT / w, CONTENT / h)
        g.transform((scale, 0, 0, scale, 0, 0))

        xmin, ymin, xmax, ymax = g.boundingBox()

        target_cx = 500
        target_cy = 500

        glyph_cx = (xmin + xmax) / 2.0
        glyph_cy = (ymin + ymax) / 2.0

        x_offset = target_cx - glyph_cx
        y_offset = target_cy - glyph_cy

        g.transform((1, 0, 0, 1, x_offset, y_offset))
        xmin, ymin, xmax, ymax = g.boundingBox()
        print("-after offset-")
        print(f"bb {xmin} {ymin} {xmax} {ymax}")

        # Set advance width to EM (monospace-like); you can also set to glyph_w + padding.
        g.width = EM_SIZE

        mappings.append((to_macro_name(svg_path), codepoint, os.path.basename(svg_path)))

    out_ttf = os.path.join(out_dir, FONT_NAME + ".ttf")
    font.generate(out_ttf)

    # Generate a C/C++ header with UTF-8 escapes using \uXXXX (PUA is in BMP -> \u)
    out_h = os.path.join(out_dir, "icons.h")
    with open(out_h, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("// Auto-generated by FontForge script. PUA range starts at U+%04X\n" % PUA_START)
        f.write("#include \"imguiex/icon.h\"\n\n")
        for macro, cp, fn in mappings:
            f.write("// %s -> U+%04X (%s)\n" % (macro, cp, fn))
            # f.write("#define %s u8\"\\u%04X\"\n" % (macro, cp))
            f.write("static auto constexpr %s = ImGuiEx::icon<0x%04X>;\n" % (macro, cp))
        f.write("\n")

    font.close()
    print("Generated:", out_ttf)
    print("Generated:", out_h)

if __name__ == "__main__":
    main()
