include(${CMAKE_CURRENT_LIST_DIR}/jamiemods.common.cmake)

set(IMGUI_INCLUDE_DIRS
   ${JAMIE_MODS_EXTERN_DIR}/imgui
   ${JAMIE_MODS_EXTERN_DIR}/imgui/backends
)
set(ImGui_Basic_Sources
   ${JAMIE_MODS_EXTERN_DIR}/imgui/imgui.h
   ${JAMIE_MODS_EXTERN_DIR}/imgui/imgui.cpp
   ${JAMIE_MODS_EXTERN_DIR}/imgui/imgui_widgets.cpp
   ${JAMIE_MODS_EXTERN_DIR}/imgui/imgui_tables.cpp
   ${JAMIE_MODS_EXTERN_DIR}/imgui/imgui_draw.cpp
)
set(ImGui_Backend_Win32_Dx11_Sources
       ${JAMIE_MODS_EXTERN_DIR}/imgui/backends/imgui_impl_win32.h
       ${JAMIE_MODS_EXTERN_DIR}/imgui/backends/imgui_impl_win32.cpp
       ${JAMIE_MODS_EXTERN_DIR}/imgui/backends/imgui_impl_dx11.h
       ${JAMIE_MODS_EXTERN_DIR}/imgui/backends/imgui_impl_dx11.cpp
)
set(ImGui_FreeType_Sources
       ${JAMIE_MODS_EXTERN_DIR}/imgui/misc/freetype/imgui_freetype.h
       ${JAMIE_MODS_EXTERN_DIR}/imgui/misc/freetype/imgui_freetype.cpp
)
set(ImGui_Demo_Sources
   ${JAMIE_MODS_EXTERN_DIR}/imgui/imgui_demo.cpp
)
